export type Lang = "NL" | "EN";

export const content = {
  NL: {
    nav: {
      about: "Over Ons",
      services: "Diensten",
      gallery: "Portfolio",
      booking: "Afspraken",
      cta: "Boek Nu",
    },
    hero: {
      badge: "Premium Autodetailing · Eindhoven",
      heading1: "Welkom bij Loox.",
      heading2: "Uw Auto, Onze Passie.",
      sub: "Premium autodetailing in Eindhoven. Wij behandelen uw auto met de zorg en aandacht die het verdient.",
      cta: "Boek een Afspraak",
      scroll: "Ontdek meer",
      stats: [
        { value: "50+", label: "Tevreden klanten" },
        { value: "5.0★", label: "Google Reviews" },
        { value: "100%", label: "Handmatig werk" },
      ],
    },
    intro: {
      badge: "Over Ons",
      heading: "Kwaliteit die je ziet en voelt.",
      body: "Bij Loox Car Detailing draait alles om precisie en passie. Gevestigd in Eindhoven leveren wij topklasse detailing aan rijders die het allerbeste willen voor hun voertuig. Elk project is uniek – wij behandelen uw auto zoals het onze eigen is. Van een grondige wasbeurt tot een perfecte high-gloss finish: wij stoppen pas als het resultaat uitstekend is.",
      body2: "Eerlijk. Vakkundig. Direct.",
      checks: [
        "Professionele apparatuur & producten",
        "Persoonlijke aanpak per voertuig",
        "Altijd transparant over prijs",
        "100% tevredenheidsgarantie",
      ],
    },
    services: {
      badge: "Diensten",
      heading: "Wat kunnen wij voor u doen?",
      from: "Vanaf",
      learnMore: "Meer informatie",
      bestSellerLabel: "Meest Gekozen",
      featured: {
        title: "Full Detailing Pakket",
        tag: "Exterieur + Interieur",
        price: "€159",
        desc: "Het complete pakket voor de rijder die het allerbeste wil. Wij behandelen uw auto van binnen én van buiten – van spiegelglanzend lak tot een vlekkeloos interieur. Eén bezoek, totaal resultaat.",
        items: [
          "Hand wash & droging",
          "Lakdecontaminatie & machine polish",
          "Sealant applicatie",
          "Dieptereiniging bekleding",
          "Dashboard & plastic behandeling",
          "Glas reinigen & geurverfrisser",
        ],
      },
      cards: [
        {
          title: "Exterieur Detailing",
          tag: "Buiten",
          price: "€79",
          desc: "Een grondige wasbeurt, ontsmetting van de lak, kleibehandeling en professioneel machine-polijsten voor een heldere, spiegelglanzende finish.",
          items: [
            "Hand wash & droging",
            "Lakdecontaminatie",
            "Machine polish",
            "Sealant applicatie",
          ],
        },
        {
          title: "Interieur Detailing",
          tag: "Binnen",
          price: "€89",
          desc: "Wij reinigen elk onderdeel van uw interieur tot in de puntjes. Van stoelen tot dashboard, vloermatten tot zijpanelen – alles stofgezogen, gereinigd en beschermd.",
          items: [
            "Dieptereiniging bekleding",
            "Dashboard & plastic behandeling",
            "Glas reinigen",
            "Geurverfrisser",
          ],
        },
      ],
    },
    gallery: {
      badge: "Portfolio",
      heading: "Ons Werk Spreekt voor Zich",
      sub: "Elke auto die onze handen verlaat, verlaat ze beter dan hij aankwam.",
    },
    booking: {
      badge: "Afspraken",
      heading: "Plan Uw Afspraak",
      sub: "Kies een datum en tijdstip dat u het beste uitkomt. Snel, eenvoudig en zonder gedoe.",
      selectDate: "Kies een datum",
      selectTime: "Kies een tijdstip",
      available: "Beschikbaar",
      confirm: "Bevestig Afspraak",
      confirmNote: "Vul uw gegevens in & kies een tijdstip",
      confirmed: "Afspraak Aangevraagd! We nemen snel contact op.",
      unavailableLabel: "Bezet",
      form: {
        name: "Uw naam",
        namePlaceholder: "Jan de Vries",
        email: "E-mailadres",
        emailPlaceholder: "jan@example.nl",
        phone: "Telefoonnummer",
        phonePlaceholder: "+31 6 ...",
      },
    },
    footer: {
      badge: "Locatie",
      heading: "Vind Ons in Eindhoven",
      address: "Ohmstraat, 5621 CW Eindhoven",
      directions:
        "Makkelijk te bereiken vanuit het centrum van Eindhoven. Gratis parkeren beschikbaar voor klanten.",
      phone: "+31 6 26000785",
      email: "info@looxdetailing.nl",
      hours: "Openingstijden",
      hoursData: [{ day: "Ma – Zo", time: "09:00 – 20:00" }],
      mapPlaceholder: "Google Maps – Eindhoven",
      follow: "Volg ons",
      rights: "Alle rechten voorbehouden.",
    },
  },

  EN: {
    nav: {
      about: "About",
      services: "Services",
      gallery: "Gallery",
      booking: "Booking",
      cta: "Book Now",
    },
    hero: {
      badge: "Premium Car Detailing · Eindhoven",
      heading1: "Welcome to Loox.",
      heading2: "Your Car, Our Passion.",
      sub: "Premium car detailing in Eindhoven. We treat your car with the care and attention it deserves.",
      cta: "Book an Appointment",
      scroll: "Discover more",
      stats: [
        { value: "50+", label: "Happy clients" },
        { value: "5.0★", label: "Google Reviews" },
        { value: "100%", label: "Hand crafted" },
      ],
    },
    intro: {
      badge: "About Us",
      heading: "Quality you see and feel.",
      body: "At Loox Car Detailing, everything is about precision and passion. Based in Eindhoven, we deliver top-class detailing to drivers who want the very best for their vehicle. Every project is unique – we treat your car as if it were our own. From a thorough wash to a perfect high-gloss finish: we don't stop until the result is outstanding.",
      body2: "Honest. Skilled. Direct.",
      checks: [
        "Professional equipment & products",
        "Personal approach per vehicle",
        "Always transparent pricing",
        "100% satisfaction guarantee",
      ],
    },
    services: {
      badge: "Services",
      heading: "What can we do for you?",
      from: "From",
      learnMore: "Learn more",
      bestSellerLabel: "Best Seller",
      featured: {
        title: "Full Detailing Package",
        tag: "Exterior + Interior",
        price: "€159",
        desc: "The complete package for the driver who wants the absolute best. We treat your car inside and out – from a mirror-shine exterior to a spotless interior. One visit, total result.",
        items: [
          "Hand wash & dry",
          "Paint decontamination & machine polish",
          "Sealant application",
          "Deep upholstery cleaning",
          "Dashboard & plastic treatment",
          "Glass cleaning & odor refresher",
        ],
      },
      cards: [
        {
          title: "Exterior Detailing",
          tag: "Outside",
          price: "€79",
          desc: "A thorough wash, paint decontamination, clay bar treatment and professional machine polishing for a clear, mirror-shine finish.",
          items: [
            "Hand wash & dry",
            "Paint decontamination",
            "Machine polish",
            "Sealant application",
          ],
        },
        {
          title: "Interior Detailing",
          tag: "Inside",
          price: "€89",
          desc: "We clean every part of your interior to perfection. From seats to dashboard, floor mats to door panels – everything vacuumed, cleaned and protected.",
          items: [
            "Deep upholstery cleaning",
            "Dashboard & plastic treatment",
            "Glass cleaning",
            "Odor refresher",
          ],
        },
      ],
    },
    gallery: {
      badge: "Portfolio",
      heading: "Our Work Speaks for Itself",
      sub: "Every car that leaves our hands, leaves better than it arrived.",
    },
    booking: {
      badge: "Booking",
      heading: "Schedule Your Appointment",
      sub: "Choose a date and time that works best for you. Quick, simple and hassle-free.",
      selectDate: "Select a date",
      selectTime: "Select a time slot",
      available: "Available",
      confirm: "Confirm Appointment",
      confirmNote: "Fill in your details & choose a time slot",
      confirmed: "Appointment Requested! We'll be in touch soon.",
      unavailableLabel: "Taken",
      form: {
        name: "Your name",
        namePlaceholder: "John Smith",
        email: "Email address",
        emailPlaceholder: "john@example.com",
        phone: "Phone number",
        phonePlaceholder: "+31 6 ...",
      },
    },
    footer: {
      badge: "Location",
      heading: "Find Us in Eindhoven",
      address: "Ohmstraat, 5621 CW Eindhoven",
      directions:
        "Easily accessible from Eindhoven city centre. Free parking available for customers.",
      phone: "+31 6 26000785",
      email: "info@looxdetailing.nl",
      hours: "Opening Hours",
      hoursData: [{ day: "Mon – Sun", time: "09:00 – 20:00" }],
      mapPlaceholder: "Google Maps – Eindhoven",
      follow: "Follow us",
      rights: "All rights reserved.",
    },
  },
} as const;
